//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.23 at 03:17:44 PM SAST 
//


package com.golden_xchange.controller.getbanknames;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.goldenriches.webservice.getbanknames package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.goldenriches.webservice.getbanknames
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBankNameListRequest }
     * 
     */
    public GetBankNameListRequest createGetBankNameListRequest() {
        return new GetBankNameListRequest();
    }

    /**
     * Create an instance of {@link GetBankNameListResponse }
     * 
     */
    public GetBankNameListResponse createGetBankNameListResponse() {
        return new GetBankNameListResponse();
    }

    /**
     * Create an instance of {@link ReturnData }
     * 
     */
    public ReturnData createReturnData() {
        return new ReturnData();
    }

}
